// api/verify.js — Vercel serverless function
// Validates a signed unlock token generated by api/checkout.js.
// Called by the app after PayFast redirects back with ?unlock=TOKEN.

import crypto from 'crypto';

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Content-Type', 'application/json');

  const token = req.query && req.query.token;
  if (!token) {
    return res.status(400).json({ valid: false, error: 'Missing token' });
  }

  try {
    const parts = token.split('.');
    if (parts.length !== 2) {
      return res.json({ valid: false, error: 'Malformed token' });
    }

    const [payload, sig] = parts;

    // Validate HMAC signature
    const expected = crypto
      .createHmac('sha256', process.env.PAYFAST_PASSPHRASE)
      .update(payload)
      .digest('base64url');

    if (expected !== sig) {
      return res.json({ valid: false, error: 'Invalid signature' });
    }

    // Decode payload
    const data = JSON.parse(Buffer.from(payload, 'base64url').toString('utf-8'));

    // Check expiry
    if (!data.expiry || new Date(data.expiry) <= new Date()) {
      return res.json({ valid: false, error: 'Token expired' });
    }

    return res.json({
      valid:  true,
      plan:   data.plan,
      expiry: data.expiry,
    });
  } catch {
    return res.json({ valid: false, error: 'Parse error' });
  }
}
